-- Generated by scripts/generate-seed.mjs from data/seed/roster.json. Do not edit by hand.
begin;

insert into public.seasons (id, name, starts_on, ends_on, is_active) values
  ('2026-27', '2026-27 Season', '2026-08-01', '2027-06-15', true)
on conflict (id) do update set name = excluded.name, starts_on = excluded.starts_on, ends_on = excluded.ends_on, is_active = excluded.is_active;

insert into public.sports (id, slug, name) values ('basketball', 'basketball', 'Basketball')
on conflict (id) do nothing;

insert into public.teams (id, sport_id, slug, name, gender, level) values
  ('bbb-v', 'basketball', 'varsity-boys-basketball', 'Varsity Boys Basketball', 'boys', 'varsity'),
  ('gbb-v', 'basketball', 'varsity-girls-basketball', 'Varsity Girls Basketball', 'girls', 'varsity'),
  ('bbb-jv', 'basketball', 'jv-boys-basketball', 'JV Boys Basketball', 'boys', 'jv'),
  ('gbb-jv', 'basketball', 'jv-girls-basketball', 'JV Girls Basketball', 'girls', 'jv')
on conflict (id) do update set slug = excluded.slug, name = excluded.name, gender = excluded.gender, level = excluded.level;

insert into public.athletes (id, slug, full_name) values
  ('ryan-j-lin', 'ryan-j-lin', 'Ryan J. Lin'),
  ('justin-lin', 'justin-lin', 'Justin Lin'),
  ('zacharia-j-chow', 'zacharia-j-chow', 'Zacharia J. Chow'),
  ('kyan-cheng', 'kyan-cheng', 'Kyan Cheng'),
  ('daniel-guo', 'daniel-guo', 'Daniel Guo'),
  ('elijah-liao', 'elijah-liao', 'Elijah Liao'),
  ('austin-dam', 'austin-dam', 'Austin Dam'),
  ('corison-kang', 'corison-kang', 'Corison Kang'),
  ('salem-chancler', 'salem-chancler', 'Salem Chancler'),
  ('oliver-ho', 'oliver-ho', 'Oliver Ho'),
  ('caleb-huang', 'caleb-huang', 'Caleb Huang'),
  ('ethan-flowers', 'ethan-flowers', 'Ethan Flowers'),
  ('maya-chen', 'maya-chen', 'Maya Chen'),
  ('emma-liu', 'emma-liu', 'Emma Liu'),
  ('sophia-wang', 'sophia-wang', 'Sophia Wang')
on conflict (id) do update set full_name = excluded.full_name;

insert into public.athlete_seasons (athlete_id, season_id, team_id, jersey_number, position, grade, height) values
  ('ryan-j-lin', '2026-27', 'bbb-v', 1, 'PG', null, '5''8"'),
  ('justin-lin', '2026-27', 'bbb-v', 2, 'G', null, '5''7"'),
  ('zacharia-j-chow', '2026-27', 'bbb-v', 3, 'SF', null, '5''10"'),
  ('kyan-cheng', '2026-27', 'bbb-v', 4, 'SG', null, '5''9"'),
  ('daniel-guo', '2026-27', 'bbb-v', 5, 'SG', null, '5''10"'),
  ('elijah-liao', '2026-27', 'bbb-v', 6, 'SF', null, '6''0"'),
  ('austin-dam', '2026-27', 'bbb-v', 7, 'PG', null, '6''0"'),
  ('corison-kang', '2026-27', 'bbb-v', 8, 'PF', null, '6''0"'),
  ('salem-chancler', '2026-27', 'bbb-v', 9, 'G', null, '5''8"'),
  ('oliver-ho', '2026-27', 'bbb-v', 12, 'SG', null, '5''10"'),
  ('caleb-huang', '2026-27', 'bbb-v', 13, 'PF', null, '5''10"'),
  ('ethan-flowers', '2026-27', 'bbb-v', 14, 'C', null, '6''1"'),
  ('maya-chen', '2026-27', 'gbb-v', 10, 'PG', null, '5''7"'),
  ('emma-liu', '2026-27', 'gbb-v', 15, 'C', null, '6''0"'),
  ('sophia-wang', '2026-27', 'gbb-v', 22, 'SF', null, '5''10"')
on conflict (athlete_id, season_id, team_id) do update set jersey_number = excluded.jersey_number, position = excluded.position, grade = excluded.grade, height = excluded.height;

commit;
