// Generates the SQL seed files from data/seed/roster.json.
//
//   supabase/seed.sql       Season, sport, the 4 MAT teams and current rosters.
//                           Safe to run on the real project (upserts).
//   supabase/demo-seed.sql  Sample opponents, games and simulated play-by-play.
//                           For local testing and demos only. Every demo row id
//                           starts with "demo-" so `delete ... like 'demo-%'`
//                           removes it cleanly.
//
// Run: npm run seed:generate

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { simulateGame } from "./lib/simulate-game.mjs";

const root = process.cwd();
const data = JSON.parse(readFileSync(path.join(root, "data", "seed", "roster.json"), "utf8"));

function sql(value) {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  return `'${String(value).replaceAll("'", "''")}'`;
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function values(rows) {
  return rows.map((row) => `  (${row.map(sql).join(", ")})`).join(",\n");
}

const { season, teams, roster } = data;
const athletes = roster.map((player) => ({ ...player, id: slugify(player.name), slug: slugify(player.name) }));

// ---------------------------------------------------------------------------
// seed.sql
// ---------------------------------------------------------------------------

const seed = [
  "-- Generated by scripts/generate-seed.mjs from data/seed/roster.json. Do not edit by hand.",
  "begin;",
  "",
  `insert into public.seasons (id, name, starts_on, ends_on, is_active) values\n${values([
    [season.id, season.name, season.startsOn, season.endsOn, true],
  ])}\non conflict (id) do update set name = excluded.name, starts_on = excluded.starts_on, ends_on = excluded.ends_on, is_active = excluded.is_active;`,
  "",
  "insert into public.sports (id, slug, name) values ('basketball', 'basketball', 'Basketball')\non conflict (id) do nothing;",
  "",
  `insert into public.teams (id, sport_id, slug, name, gender, level) values\n${values(
    teams.map((team) => [team.id, "basketball", team.slug, team.name, team.gender, team.level]),
  )}\non conflict (id) do update set slug = excluded.slug, name = excluded.name, gender = excluded.gender, level = excluded.level;`,
  "",
  `insert into public.athletes (id, slug, full_name) values\n${values(
    athletes.map((athlete) => [athlete.id, athlete.slug, athlete.name]),
  )}\non conflict (id) do update set full_name = excluded.full_name;`,
  "",
  `insert into public.athlete_seasons (athlete_id, season_id, team_id, jersey_number, position, grade, height) values\n${values(
    athletes.map((athlete) => [
      athlete.id,
      season.id,
      athlete.team,
      athlete.number ?? null,
      athlete.position ?? null,
      athlete.grade ?? null,
      athlete.height ?? null,
    ]),
  )}\non conflict (athlete_id, season_id, team_id) do update set jersey_number = excluded.jersey_number, position = excluded.position, grade = excluded.grade, height = excluded.height;`,
  "",
  "commit;",
  "",
];

writeFileSync(path.join(root, "supabase", "seed.sql"), seed.join("\n"));

// ---------------------------------------------------------------------------
// demo-seed.sql
// ---------------------------------------------------------------------------

const opponents = [
  ["demo-tigers", "Taipei Academy Tigers", "Tigers"],
  ["demo-huskies", "Riverdale Huskies", "Huskies"],
  ["demo-knights", "Summit Prep Knights", "Knights"],
  ["demo-eagles", "Lakeside Eagles", "Eagles"],
];

const boys = athletes.filter((athlete) => athlete.team === "bbb-v").map((athlete) => athlete.id);

// [id, team, opponent, is_home, start offset, location, status, scoring_mode, simulation]
const games = [
  {
    id: "demo-final-knights",
    team: "bbb-v",
    opponent: "demo-knights",
    isHome: true,
    startsAt: "now() - interval '6 days'",
    location: "Morrison Gym",
    status: "final",
    simulation: { seed: 7, periods: 4 },
    clock: { period: 4, secondsLeft: 0 },
  },
  {
    id: "demo-live-huskies",
    team: "bbb-v",
    opponent: "demo-huskies",
    isHome: false,
    startsAt: "now() - interval '40 minutes'",
    location: "Riverdale Gym",
    status: "live",
    simulation: { seed: 21, periods: 3, stopAtSecondsLeft: 214 },
    clock: { period: 3, secondsLeft: 214 },
  },
  {
    id: "demo-upcoming-tigers",
    team: "bbb-v",
    opponent: "demo-tigers",
    isHome: true,
    startsAt: "date_trunc('day', now()) + interval '3 days 18 hours'",
    location: "Morrison Gym",
    status: "scheduled",
  },
  {
    id: "demo-final-eagles",
    team: "gbb-v",
    opponent: "demo-eagles",
    isHome: false,
    startsAt: "now() - interval '9 days'",
    location: "Lakeside Gym",
    status: "final",
    manualScore: [54, 48],
  },
];

const demo = [
  "-- Generated by scripts/generate-seed.mjs. DEMO DATA ONLY: never run this on the real project.",
  "-- Remove with: delete from public.games where id like 'demo-%'; delete from public.opponents where id like 'demo-%';",
  "begin;",
  "",
  `insert into public.opponents (id, name, short_name) values\n${values(opponents)}\non conflict (id) do nothing;`,
  "",
];

for (const game of games) {
  const manual = Boolean(game.manualScore);
  demo.push(
    `insert into public.games (id, season_id, team_id, opponent_id, is_home, starts_at, location, status, scoring_mode, team_score, opponent_score, current_period, clock_seconds_left) values\n` +
      `  (${sql(game.id)}, ${sql(season.id)}, ${sql(game.team)}, ${sql(game.opponent)}, ${game.isHome}, ${game.startsAt}, ${sql(game.location)}, ${sql(game.status)}, ${sql(manual ? "manual" : "live")}, ${game.manualScore?.[0] ?? 0}, ${game.manualScore?.[1] ?? 0}, ${game.clock?.period ?? 1}, ${game.clock?.secondsLeft ?? 480})\n` +
      "on conflict (id) do nothing;",
  );

  if (game.simulation) {
    const events = simulateGame({ athleteIds: boys, ...game.simulation });
    const rows = events.map(
      (event) =>
        `  (${sql(game.id)}, ${sql(event.side)}, ${sql(event.athlete_id)}, ${sql(event.event_type)}, ${event.period}, ${event.clock_seconds_left}, ${sql(event.shot_x)}, ${sql(event.shot_y)}, (${game.startsAt}) + interval '${event.offset_seconds} seconds')`,
    );
    demo.push(
      `insert into public.game_events (game_id, side, athlete_id, event_type, period, clock_seconds_left, shot_x, shot_y, created_at) values\n${rows.join(",\n")};`,
    );
  }
  demo.push("");
}

demo.push("commit;", "");
writeFileSync(path.join(root, "supabase", "demo-seed.sql"), demo.join("\n"));

console.log(`seed.sql: ${teams.length} teams, ${athletes.length} athletes`);
console.log(`demo-seed.sql: ${opponents.length} opponents, ${games.length} games`);
