// Generates the SQL seed files from data/seed/roster.json.
//
//   supabase/seed.sql       Season, sport, the 4 MAT teams and current rosters.
//                           Safe to run on the real project (upserts).
//   supabase/demo-seed.sql  Sample opponents, games and simulated play-by-play.
//                           For local testing and demos only. Every demo row id
//                           starts with "demo-" so `delete ... like 'demo-%'`
//                           removes it cleanly.
//
// Run: npm run seed:generate

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { simulateGame } from "./lib/simulate-game.mjs";

const root = process.cwd();
const data = JSON.parse(readFileSync(path.join(root, "data", "seed", "roster.json"), "utf8"));

function sql(value) {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  return `'${String(value).replaceAll("'", "''")}'`;
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function values(rows) {
  return rows.map((row) => `  (${row.map(sql).join(", ")})`).join(",\n");
}

const { season, teams, roster } = data;
const athletes = roster.map((player) => ({ ...player, id: slugify(player.name), slug: slugify(player.name) }));

// ---------------------------------------------------------------------------
// seed.sql
// ---------------------------------------------------------------------------

const seed = [
  "-- Generated by scripts/generate-seed.mjs from data/seed/roster.json. Do not edit by hand.",
  "begin;",
  "",
  `insert into public.seasons (id, name, starts_on, ends_on, is_active) values\n${values([
    [season.id, season.name, season.startsOn, season.endsOn, true],
  ])}\non conflict (id) do update set name = excluded.name, starts_on = excluded.starts_on, ends_on = excluded.ends_on, is_active = excluded.is_active;`,
  "",
  "insert into public.sports (id, slug, name) values ('basketball', 'basketball', 'Basketball')\non conflict (id) do nothing;",
  "",
  `insert into public.teams (id, sport_id, slug, name, gender, level) values\n${values(
    teams.map((team) => [team.id, "basketball", team.slug, team.name, team.gender, team.level]),
  )}\non conflict (id) do update set slug = excluded.slug, name = excluded.name, gender = excluded.gender, level = excluded.level;`,
  "",
  `insert into public.athletes (id, slug, full_name) values\n${values(
    athletes.map((athlete) => [athlete.id, athlete.slug, athlete.name]),
  )}\non conflict (id) do update set full_name = excluded.full_name;`,
  "",
  `insert into public.athlete_seasons (athlete_id, season_id, team_id, jersey_number, position, grade, height) values\n${values(
    athletes.map((athlete) => [
      athlete.id,
      season.id,
      athlete.team,
      athlete.number ?? null,
      athlete.position ?? null,
      athlete.grade ?? null,
      athlete.height ?? null,
    ]),
  )}\non conflict (athlete_id, season_id, team_id) do update set jersey_number = excluded.jersey_number, position = excluded.position, grade = excluded.grade, height = excluded.height;`,
  "",
  "commit;",
  "",
];

writeFileSync(path.join(root, "supabase", "seed.sql"), seed.join("\n"));

// ---------------------------------------------------------------------------
// demo-seed.sql
// ---------------------------------------------------------------------------

const opponents = [
  ["demo-tigers", "Taipei Academy Tigers", "Tigers"],
  ["demo-huskies", "Riverdale Huskies", "Huskies"],
  ["demo-knights", "Summit Prep Knights", "Knights"],
  ["demo-eagles", "Lakeside Eagles", "Eagles"],
  ["demo-falcons", "South Valley Falcons", "Falcons"],
  ["demo-panthers", "Westbrook Panthers", "Panthers"],
];

const boys = athletes.filter((athlete) => athlete.team === "bbb-v").map((athlete) => athlete.id);

// Different players lead different games: rotate who the simulator favours.
function rotated(ids, by) {
  const shift = by % ids.length;
  return [...ids.slice(shift), ...ids.slice(0, shift)];
}

// Start times are relative to when the seed is loaded, so the demo always looks current.
const DAY = 86400;
const HOUR = 3600;
const final = (id, team, opponent, isHome, daysAgo, seed, location) => ({
  id,
  team,
  opponent,
  isHome,
  startsIn: -daysAgo * DAY,
  location,
  status: "final",
  simulation: { seed, periods: 4, athleteIds: rotated(boys, seed) },
  clock: { period: 4, secondsLeft: 0 },
});
const manualFinal = (id, team, opponent, isHome, daysAgo, score, location) => ({
  id,
  team,
  opponent,
  isHome,
  startsIn: -daysAgo * DAY,
  location,
  status: "final",
  manualScore: score,
});
const upcoming = (id, team, opponent, isHome, startsIn, location) => ({
  id,
  team,
  opponent,
  isHome,
  startsIn,
  roundToHour: true,
  location,
  status: "scheduled",
});

const games = [
  // Boys Varsity: a run of tracked games, one live now, two coming up.
  final("demo-final-falcons", "bbb-v", "demo-falcons", true, 34, 3, "Morrison Gym"),
  final("demo-final-panthers", "bbb-v", "demo-panthers", false, 27, 11, "Westbrook Gym"),
  final("demo-final-eagles-b", "bbb-v", "demo-eagles", true, 20, 5, "Morrison Gym"),
  final("demo-final-tigers-b", "bbb-v", "demo-tigers", false, 13, 17, "Taipei Academy"),
  final("demo-final-knights", "bbb-v", "demo-knights", true, 6, 7, "Morrison Gym"),
  {
    id: "demo-live-huskies",
    team: "bbb-v",
    opponent: "demo-huskies",
    isHome: false,
    startsIn: -40 * 60,
    location: "Riverdale Gym",
    status: "live",
    simulation: { seed: 21, periods: 3, stopAtSecondsLeft: 214, athleteIds: rotated(boys, 2) },
    clock: { period: 3, secondsLeft: 214 },
  },
  upcoming("demo-upcoming-tigers", "bbb-v", "demo-tigers", true, 1 * DAY + 3 * HOUR, "Morrison Gym"),
  upcoming("demo-upcoming-falcons", "bbb-v", "demo-falcons", false, 8 * DAY, "South Valley Gym"),
  // Other teams: results typed in (no operator), so records still add up.
  manualFinal("demo-final-eagles", "gbb-v", "demo-eagles", false, 9, [54, 48], "Lakeside Gym"),
  manualFinal("demo-final-panthers-g", "gbb-v", "demo-panthers", true, 16, [41, 47], "Morrison Gym"),
  upcoming("demo-upcoming-tigers-g", "gbb-v", "demo-tigers", true, 2 * DAY + 2 * HOUR, "Morrison Gym"),
  manualFinal("demo-final-knights-jv", "bbb-jv", "demo-knights", true, 11, [38, 35], "Morrison Gym"),
  upcoming("demo-upcoming-eagles-jv", "bbb-jv", "demo-eagles", false, 5 * DAY, "Lakeside Gym"),
  manualFinal("demo-final-falcons-jvg", "gbb-jv", "demo-falcons", false, 12, [29, 33], "South Valley Gym"),
];

const news = [
  {
    slug: "demo-senior-night",
    title: "Senior Night this Friday: Broncos host the Tigers",
    category: "game-day",
    summary: "Come out early to honor our seniors before tip-off. Wear green!",
    body: "Senior Night ceremonies start 20 minutes before tip-off in the Morrison Gym.\n\nFamilies of seniors, please arrive by 4:30 PM.",
    team: "bbb-v",
    pinned: true,
    daysAgo: 1,
  },
  {
    slug: "demo-bus-change",
    title: "Bus time change for Saturday's away games",
    category: "transportation",
    summary: "Buses now leave at 7:15 AM from the front gate.",
    body: "Because of road work, buses for Saturday's away games leave 15 minutes earlier, at 7:15 AM from the front gate.",
    team: null,
    pinned: false,
    daysAgo: 3,
  },
  {
    slug: "demo-knights-recap",
    title: "Broncos fall 51–52 to Knights in a one-point thriller",
    category: "team-news",
    summary: "A late Knights bucket decided a game that featured eleven lead changes.",
    body: "The Broncos battled back from an early deficit but came up one point short against Summit Prep.\n\nFull box score and shot chart are on the game page.",
    team: "bbb-v",
    pinned: false,
    daysAgo: 6,
  },
];

for (const game of games) {
  game.events = game.simulation ? simulateGame({ athleteIds: boys, ...game.simulation }) : [];
}

function startsAtSql(game) {
  const expression = `now() + interval '${game.startsIn} seconds'`;
  return game.roundToHour ? `date_trunc('hour', ${expression})` : `(${expression})`;
}

const demo = [
  "-- Generated by scripts/generate-seed.mjs. DEMO DATA ONLY: never run this on the real project.",
  "-- Remove with:",
  "--   delete from public.games where id like 'demo-%';",
  "--   delete from public.opponents where id like 'demo-%';",
  "--   delete from public.announcements where slug like 'demo-%';",
  "begin;",
  "",
  `insert into public.opponents (id, name, short_name) values\n${values(opponents)}\non conflict (id) do nothing;`,
  "",
];

for (const game of games) {
  const manual = Boolean(game.manualScore);
  demo.push(
    `insert into public.games (id, season_id, team_id, opponent_id, is_home, starts_at, location, status, scoring_mode, team_score, opponent_score, current_period, clock_seconds_left) values\n` +
      `  (${sql(game.id)}, ${sql(season.id)}, ${sql(game.team)}, ${sql(game.opponent)}, ${game.isHome}, ${startsAtSql(game)}, ${sql(game.location)}, ${sql(game.status)}, ${sql(manual ? "manual" : "live")}, ${game.manualScore?.[0] ?? 0}, ${game.manualScore?.[1] ?? 0}, ${game.clock?.period ?? 1}, ${game.clock?.secondsLeft ?? 480})\n` +
      "on conflict (id) do nothing;",
  );

  if (game.events.length) {
    const rows = game.events.map(
      (event) =>
        `  (${sql(game.id)}, ${sql(event.side)}, ${sql(event.athlete_id)}, ${sql(event.event_type)}, ${event.period}, ${event.clock_seconds_left}, ${sql(event.shot_x)}, ${sql(event.shot_y)}, ${startsAtSql(game)} + interval '${event.offset_seconds} seconds')`,
    );
    demo.push(
      `insert into public.game_events (game_id, side, athlete_id, event_type, period, clock_seconds_left, shot_x, shot_y, created_at) values\n${rows.join(",\n")};`,
    );
  }
  demo.push("");
}

demo.push(
  `insert into public.announcements (slug, title, category, summary, body, team_id, pinned, published_at) values\n${news
    .map((item) => `  (${[item.slug, item.title, item.category, item.summary, item.body, item.team, item.pinned].map(sql).join(", ")}, now() - interval '${item.daysAgo} days')`)
    .join(",\n")}\non conflict (slug) do nothing;`,
  "",
);

demo.push("commit;", "");
writeFileSync(path.join(root, "supabase", "demo-seed.sql"), demo.join("\n"));

// ---------------------------------------------------------------------------
// data/seed/demo.json: the same demo data for the app's demo mode (no Supabase)
// ---------------------------------------------------------------------------

const demoJson = {
  generatedBy: "scripts/generate-seed.mjs",
  season,
  teams,
  roster: athletes.map((athlete) => ({
    athleteId: athlete.id,
    slug: athlete.slug,
    name: athlete.name,
    teamId: athlete.team,
    number: athlete.number ?? null,
    position: athlete.position ?? null,
    grade: athlete.grade ?? null,
    height: athlete.height ?? null,
  })),
  opponents: opponents.map(([id, name, shortName]) => ({ id, name, shortName })),
  news: news.map((item) => ({
    slug: item.slug,
    title: item.title,
    category: item.category,
    summary: item.summary,
    body: item.body.replaceAll("\\n", "\n"),
    teamId: item.team,
    pinned: item.pinned,
    daysAgo: item.daysAgo,
  })),
  games: games.map((game) => ({
    id: game.id,
    teamId: game.team,
    opponentId: game.opponent,
    isHome: game.isHome,
    startsIn: game.startsIn,
    roundToHour: Boolean(game.roundToHour),
    location: game.location,
    status: game.status,
    scoringMode: game.manualScore ? "manual" : "live",
    manualScore: game.manualScore ?? null,
    currentPeriod: game.clock?.period ?? 1,
    clockSecondsLeft: game.clock?.secondsLeft ?? 480,
    events: game.events.map((event) => ({
      side: event.side,
      athleteId: event.athlete_id,
      type: event.event_type,
      period: event.period,
      clockSecondsLeft: event.clock_seconds_left,
      shotX: event.shot_x,
      shotY: event.shot_y,
      offsetSeconds: event.offset_seconds,
    })),
  })),
};

writeFileSync(path.join(root, "data", "seed", "demo.json"), `${JSON.stringify(demoJson)}\n`);

console.log(`seed.sql: ${teams.length} teams, ${athletes.length} athletes`);
console.log(`demo-seed.sql + demo.json: ${opponents.length} opponents, ${games.length} games`);
